import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { Timeline } from "../components/timeline";
import { AnimateIntroduction } from "../components/animateIntroduction";
import { INTRODUCTION } from "../data/textIntro";
import { TIMELINES_DATA } from "../data/timelineData";

const Home: NextPage = () => {
  const [introductionIndex, setIntroductionIndex] = useState(0);

  const updateDataIndex = () => {
    if (introductionIndex < INTRODUCTION.length - 1) {
      setIntroductionIndex((prev) => prev + 1);
    } else {
      setIntroductionIndex(0);
    }
  };

  return (
    <div>
      <Head>
        <title>Enzo Hespel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Scada&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="container mx-auto mt-8 px-8">
        <div className="flex mb-9">
          <p className="mr-1 cursor-pointer">Français</p>
          <span className="mr-1">-</span>
          <p className="underline cursor-pointer">Anglais</p>
        </div>
        <AnimateIntroduction
          updateDataIndex={updateDataIndex}
          title={INTRODUCTION[introductionIndex].title}
          subtitle={INTRODUCTION[introductionIndex].subtitle}
          text={INTRODUCTION[introductionIndex].text}
        />

        <div className="grid gap-8 md:gap-16  grid-cols-1 md:grid-cols-2">
          {TIMELINES_DATA.map((timeline, i) => (
            <Timeline
              key={i}
              timelineCategory={timeline.category}
              timelineData={timeline.data}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
