import type { NextPage } from "next";
import Head from "next/head";

import { Timeline } from "../components/timeline";
import { AnimateIntroduction } from "../components/animateIntroduction";
import { INTRODUCTION } from "../data/textIntro";
import { TIMELINES_DATA } from "../data/timelineData";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Enzo Hespel</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" sizes="16x16" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700;800&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Scada&display=swap"
        rel="stylesheet"
      ></link>
    </Head>

    <main className="container mx-auto mt-8 px-8">
      <div className="flex mb-9">
        <p className="mr-1 cursor-pointer">Français</p>
        <span className="mr-1">-</span>
        <p className="underline cursor-pointer">Anglais</p>
      </div>
      <AnimateIntroduction data={INTRODUCTION} />

      <div className="grid gap-8 lg:gap-16  grid-cols-1 lg:grid-cols-2">
        {TIMELINES_DATA.map((timeline, i) => (
          <Timeline
            key={i}
            timelineCategory={timeline.category}
            timelineData={timeline.data}
          />
        ))}
      </div>
    </main>
  </div>
);

export default Home;
