import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { ProgressBar } from "../components/progressBar";

const Home: NextPage = () => {
  const [dataIndex, setDataIndex] = useState(0);

  const data = [
    { title: "titre1", subtitle: "subtitle1", text: "text1" },
    { title: "titre2", subtitle: "subtitle2", text: "text2" },
    { title: "titre3", subtitle: "subtitle3", text: "text3" },
  ];

  const updateDataIndex = () => {
    if (dataIndex < 2) {
      setDataIndex((prev) => prev + 1);
    } else {
      setDataIndex(0);
    }
  };

  return (
    <div>
      <Head>
        <title>Enzo Hespel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto mt-8">
        <div className="flex mb-9">
          <p className="mr-1 cursor-pointer">Français</p>
          <span className="mr-1">-</span>
          <p className="underline cursor-pointer">Anglais</p>
        </div>
        <div className="w-1/3">
          <h2 className="text-3xl font-bold mb-1">
            <div>{data[dataIndex].title}</div>
            <div className="text-3xl font-bold mb-1">
              {data[dataIndex].subtitle}
            </div>
          </h2>
          <ProgressBar onFinish={updateDataIndex} />
          <p>{data[dataIndex].text}</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
